language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - pyinstaller fetchrepos.py
  
notifications:
  email:
    - tahtaciburak@github.com
